- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure load balancer
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      upstream web_backend {
          server 192.168.56.101;
          server 192.168.56.102;
      }

      server {
          listen 80;

          location / {
              proxy_pass http://web_backend;
          }
      }

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
