- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure LB
  template:
    src: lb.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
