- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create Web Page
  copy:
    dest: /var/www/html/index.html
    content: "<h1>{{ inventory_hostname }}</h1>"

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
