---
- name: Deploy All Infrastructure
  hosts: all
  become: true
  gather_facts: true

  roles:
    - { role: lb, when: "'lb' in inventory_hostname" }
    - { role: web, when: "'web' in inventory_hostname" }
    - { role: db, when: "'db' in inventory_hostname" }
